### PR TITLE
(fix) Remove attribute binding on `value`

### PR DESCRIPTION
**Pull request by wmadden**
Because of this attribute binding, assigning a date to the component's `value` attribute will cause Ember to assign the date to the underlying `<input>`'s value attribute, which is in the best case useless.

Flatpickr will then overwrite this value, except in some cases, where the visible string will become the Date instance cast to a string (i.e. default JavaScript date string formatting).

### CODE REVIEW

**Comment by rwwagner90** [comment]
Does this fix the issue you filed @wmadden?

**Comment by wmadden** [comment]
@rwwagner90 no, this is a different bug. Here's a twiddle demonstrating the bug this PR addresses: https://ember-twiddle.com/c1c420acd3cb4c914199a4b5a1daa155

**Comment by wmadden** [comment]
Unfortunately removing the attribute binding broke a bunch of tests. I'd love some assistance debugging the tests.

**Comment by wmadden** [comment]
Actually, none of the tests seem to pass on master either so I don't think it's anything I changed in this PR. @rwwagner90 it'd be great if you could take a look. 

I did some debugging in the tests and I believe the problem is caused by the `flatpickrRef` used [here](https://github.com/shipshapecode/ember-flatpickr/blob/master/tests/integration/components/ember-flatpickr-test.js#L289). This two-way binding means that when the first rendered `ember-flatpickr` component initializes, it sets the `flatpickrRef` attribute on the test view. That value contains the flatpickr instance which is torn down when `willDestroyElement()` is called. After that point, any calls to the flatpickr instance (e.g. `setDate()`) will raise an exception.

Unfortunately, because the `flatpickrRef` value is stored on the _test instance_, it is then assigned to each subsequently-rendered `ember-flatpickr` component - overriding the new flatpickr instances they create during initialization.

A couple of obvious solutions to this problem spring to mind. The simplest is to have one expectation per test - i.e. split the test function [here](https://github.com/shipshapecode/ember-flatpickr/blob/master/tests/integration/components/ember-flatpickr-test.js#L277) so that there's only one render block per test.

However a more elegant solution would be to not use the `flatpickrRef` at all. Moreover, you're testing the functionality of the flatpickr library ("value accepts string, dateObject or array of string/dateObjects"). If I were you I'd delete the test entirely since it _doesn't_ test what your library is actually testing and _does_ test what flatpickr is doing.

**Comment by rwwagner90** [comment]
@wmadden I don't think that the flatpickrRef binding has anything to do with it, as these tests historically worked. It's something about changes in the newer versions of flatpickr that caused issues. I'm going to work on debugging it.

I'm not sure I agree with changing from a `TextField` to a `Component`. What is the reasoning behind that?

**Comment by wmadden** [comment]
The reasoning behind using `Component` instead of `TextField` is that `TextField` has an `attributeBindings` array of its own which already includes `'value'`.

**Comment by rwwagner90** [comment]
Thanks for all the work here! I ultimately had to tweak a few things, so I pulled in some of these changes and not others.

**Pull request closed without merging**
