### PR TITLE
Flatpickr as mixin

### PR DESCRIPTION
**Pull request by betocantu93**
This is a work in progress and to be honest, I'm not familiar with yuidocs and the build was breaking and I didn't had the time to dig into it, but basically this refactor mimics the `ember-pikaday` approach to use a mixin so we can compose components, with this mixin I can for example extend / hook `ember-paper`'s `paper-input` and use all the validations, dom and css from it

```javascript
import FlatpickrMixin from 'ember-flatpickr/mixins/flatpickr';
import PaperInput from 'ember-paper/components/paper-input';
import layout from 'ember-paper/templates/components/paper-input';

export default PaperInput.extend(FlatpickrMixin, {
   layout, 
   didInsertElement() {
     this._super(...arguments);
     let field = this.element.querySelector('input');
     this.set('field', field);
     this.setupComponent();
   }
});

```
Please, let me know what you think

### CODE REVIEW

**Comment by rwwagner90** [comment]
@betocantu93 I think this sounds like a good idea. Please let me know when you have it ready for me to review.

**Comment by betocantu93** [comment]
@rwwagner90 here is a working addon using my fork [ember-paper-flatpickr](https://github.com/betocantu93/ember-paper-flatpickr)

**Comment by rwwagner90** [comment]
This more or less looks good. I am going to merge, then clean some things up later. Thanks for the PR!

**Comment by betocantu93** [comment]
Excellent, thanks @rwwagner90

**Pull request merged**
